
# This file defines a SecretStore for Azure Key Vault and an ExternalSecret to fetch secrets from it.
# Make sure to replace tenantId with your actual Azure tenant ID.
apiVersion: external-secrets.io/v1beta1 # Ensure this matches your installed version of External Secrets Operator
kind: SecretStore # This defines a SecretStore resource
metadata: # Name of the SecretStore
  name: azure-kv-store # This is the name of the SecretStore
spec: # Specification for the SecretStore
  # Define the provider as Azure Key Vault
  provider: # Azure Key Vault provider
    azurekv: # Azure Key Vault configuration
      # Specify the tenant ID for Azure authentication
      tenantId: 3a8d282d-ac50-4234-ad09-23939955e7a3 # Replace with your actual tenant ID
      # URL of the Azure Key Vault instance
      vaultUrl: https://react-express-kv.vault.azure.net/
      # Authentication type for accessing Azure Key Vault
      # Workload Identity is used for Kubernetes workloads to access Azure resources
      authType: WorkloadIdentity # Authentication type for Azure Key Vault



apiVersion: external-secrets.io/v1beta1 # Ensure this matches your installed version of External Secrets Operator
kind: ExternalSecret # This defines an ExternalSecret resource
metadata: # Name of the ExternalSecret
  name: backend-secret # This is the name of the ExternalSecret
spec: # Specification for the ExternalSecret
  refreshInterval: 1h # Interval to refresh the secret from Azure Key Vault
  secretStoreRef: # Reference to the SecretStore where the secrets are stored
    name: azure-kv-store # Name of the SecretStore 
    kind: SecretStore # Kind of the SecretStore
  target: # Target where the secret will be created in Kubernetes
    name: backend-secret # Name of the Kubernetes secret to be created
    creationPolicy: Owner # Creation policy for the secret
  data: # Data to be fetched from Azure Key Vault
    - secretKey: db_connection_string # Key in the Kubernetes secret
      remoteRef: # Reference to the secret in Azure Key Vault
        key: dbConnectionString # Name of the secret in Azure Key Vault
