apiVersion: external-secrets.io/v1beta1 # Backend Secret
kind: ExternalSecret # Backend Secret 
metadata: # Backend Secret Metadata
  name: backend-secret # Name of the Backend Secret
spec: # Backend Secret Specification
  refreshInterval: 1h # Refresh interval for the secret
  secretStoreRef: # Reference to the Secret Store
    name: azure-kv-store # Name of the Secret Store
    kind: SecretStore # Kind of the Secret Store
  target: # Target for the secret
    name: backend-secret # Name of the target secret
    creationPolicy: Owner # Creation policy for the secret
  data: # Data for the secret
    - secretKey: DB_CONNECTION_STRING # Key for the secret
      remoteRef: # Reference to the remote secret
        key: sqlConnectionString # Key of the remote secret