apiVersion: external-secrets.io/v1beta1 # Ensure this matches your installed version
kind: SecretStore # This is the kind for Azure Key Vault Secret Store
metadata: # This metadata is used to identify the resource
  name: azure-kv-store # Name of the SecretStore
spec: # Specification for the SecretStore
  provider: # Provider configuration
    azurekv: # Azure Key Vault specific configuration
      authType: WorkloadIdentity # Authentication type
      vaultUrl: https://react-express-kv.vault.azure.net/ # URL of the Azure Key Vault